entrypoints:
  - src/index.js
aliases:
  generated:
    - "src/generated/**"
    - "generated/**"
  common:
    - "src/@*/**"
    - "src/config.js"
    - "src/common.js"
allow:
  "src/users/**":
    - "src/users/**"
    - "common"
deny:
  "src/products/**":
    - "src/users/**"
    - "common"
    - "generated"
