name: Release
on:
  push:
    tags:
      - 'v**'
jobs:
  create-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0' # https://github.com/actions/checkout/issues/217
          token: ${{ secrets.CI_TOKEN }}
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

  release-github-action:
    runs-on: ubuntu-22.04
    needs:
      - create-release
    steps:
      - uses: actions/checkout@v3
        with:
          repository: gabotechs/dep-tree-action
          token: ${{ secrets.CI_TOKEN }}
      - run: |
          VERSION="${GITHUB_REF_NAME:1}"
          jq ".version=\"$VERSION\"" package.json > _package.json
          mv _package.json package.json
          git config --global user.email $(git --no-pager show -s --format='%ae' HEAD)
          git config --global user.name  $(git --no-pager show -s --format='%an' HEAD)
          git commit -a -m "bump: version $VERSION"
          git push origin main
          git tag "v$VERSION"
          git push --tags

  release-node-wrapper:
    runs-on: ubuntu-22.04
    needs:
      - create-release
    steps:
      - uses: actions/checkout@v3
        with:
          repository: gabotechs/node-dep-tree
          token: ${{ secrets.CI_TOKEN }}
      - run: |
          VERSION="${GITHUB_REF_NAME:1}"
          jq ".version=\"$VERSION\"" package.json > _package.json
          mv _package.json package.json
          git config --global user.email $(git --no-pager show -s --format='%ae' HEAD)
          git config --global user.name  $(git --no-pager show -s --format='%an' HEAD)
          git commit -a -m "bump: version $VERSION"
          git push origin main

  release-python-wrapper:
    runs-on: ubuntu-22.04
    needs:
      - create-release
    steps:
      - uses: actions/checkout@v3
        with:
          repository: gabotechs/python-dep-tree
          token: ${{ secrets.CI_TOKEN }}
      - run: |
          VERSION="${GITHUB_REF_NAME:1}"
          sed "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml > _pyproject.toml
          mv _pyproject.toml pyproject.toml
          sed "s/__version__ = '.*'/__version__ = '$VERSION'/" dep_tree/main.py > dep_tree/_main.py
          mv dep_tree/_main.py dep_tree/main.py
          git config --global user.email $(git --no-pager show -s --format='%ae' HEAD)
          git config --global user.name  $(git --no-pager show -s --format='%an' HEAD)
          git commit -a -m "bump: version $VERSION"
          git push origin main
